# Generated by Django 3.0.7 on 2020-12-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
